package core

import (
	"strconv"
	"strings"
)

// TaskRef addresses a task either by its stable identifier or by its
// human-readable per-project reference such as "infra-42".
//
// Both forms are accepted everywhere a task is addressed. The human form is
// what people type and what appears in commit messages; the stable form is what
// survives a project being renamed.
type TaskRef struct {
	// ID is the stable identifier, set when the ref was given in that form.
	ID string
	// ProjectKey and Seq are set when the ref was given in human form.
	ProjectKey string
	Seq        int64
}

// IsID reports whether the ref addresses a task by stable identifier.
func (r TaskRef) IsID() bool { return r.ID != "" }

// String renders the ref in the form it was parsed from.
func (r TaskRef) String() string {
	if r.IsID() {
		return r.ID
	}
	if r.ProjectKey == "" {
		return ""
	}
	return r.ProjectKey + "-" + strconv.FormatInt(r.Seq, 10)
}

// Valid reports whether the ref addresses anything.
func (r TaskRef) Valid() bool {
	return r.IsID() || (r.ProjectKey != "" && r.Seq > 0)
}

// ParseTaskRef parses a task reference.
//
// A value containing a hyphen followed by digits is read as a human reference,
// splitting at the LAST hyphen so project keys may themselves contain hyphens
// ("web-api-7" is task 7 of project "web-api"). Anything else is treated as a
// stable identifier.
func ParseTaskRef(s string) (TaskRef, error) {
	s = strings.TrimSpace(s)
	if s == "" {
		return TaskRef{}, Invalid("empty task reference")
	}

	if i := strings.LastIndex(s, "-"); i > 0 && i < len(s)-1 {
		key, num := s[:i], s[i+1:]
		if seq, err := strconv.ParseInt(num, 10, 64); err == nil {
			if seq <= 0 {
				return TaskRef{}, Invalid("task reference %q has a non-positive number", s)
			}
			if !validProjectKey(key) {
				return TaskRef{}, Invalid("task reference %q has an invalid project key", s)
			}
			return TaskRef{ProjectKey: strings.ToLower(key), Seq: seq}, nil
		}
	}

	if !validID(s) {
		return TaskRef{}, Invalid("task reference %q is not a valid identifier or project reference", s)
	}
	return TaskRef{ID: s}, nil
}

// MustParseTaskRef parses a reference, panicking on failure. For tests and
// package-level variables only.
func MustParseTaskRef(s string) TaskRef {
	r, err := ParseTaskRef(s)
	if err != nil {
		panic(err)
	}
	return r
}

// validProjectKey reports whether s is a usable project key: letters, digits,
// hyphens and underscores, starting with a letter and ending with a letter or
// digit. The trailing rule matters: without it "infra--5" would split into the
// key "infra-" and sequence 5 rather than being rejected.
func validProjectKey(s string) bool {
	if s == "" || len(s) > 64 {
		return false
	}
	for i, c := range s {
		switch {
		case c >= 'a' && c <= 'z', c >= 'A' && c <= 'Z':
		case c >= '0' && c <= '9', c == '-', c == '_':
			if i == 0 {
				return false
			}
		default:
			return false
		}
	}
	if last := s[len(s)-1]; last == '-' || last == '_' {
		return false
	}
	return true
}

// ValidateProjectKey returns an error describing why s is not a usable project key.
func ValidateProjectKey(s string) error {
	if !validProjectKey(s) {
		return Invalid("project key %q must start with a letter, end with a letter or digit, and contain only letters, digits, hyphens and underscores", s)
	}
	return nil
}

// validID reports whether s looks like a stable identifier. Identifiers are
// generated by internal/id as Crockford base32, so the character set is
// restricted; rejecting anything else keeps a stray shell glob or a URL from
// being taken for an identifier.
func validID(s string) bool {
	if len(s) < 8 || len(s) > 64 {
		return false
	}
	for _, c := range s {
		switch {
		case c >= '0' && c <= '9':
		case c >= 'A' && c <= 'Z':
		case c >= 'a' && c <= 'z':
		default:
			return false
		}
	}
	return true
}
