// SPDX-License-Identifier: AGPL-3.0-or-later

package cmd

import (
	"slices"
	"strings"
	"testing"

	"github.com/heliopsy/tix/internal/docsmd"
)

// The comment carried around the command table claims the block is generated.
// Nothing enforced it, so the table lost a row and kept the claim: the block
// had no `tix demo` line for as long as anybody looked. The table lives in
// docs/commands.md since README.md was split; the guard follows the block
// rather than the file it used to sit in.
const (
	beginCommands = "<!-- BEGIN COMMANDS: generated by `tix docs --table`, do not edit by hand -->"
	endCommands   = "<!-- END COMMANDS -->"

	// docsmd.Read resolves from the repository root, not the package directory.
	commandTableFile = "docs/commands.md"
)

// TestReadmeCommandTableMatchesTheCommandTree regenerates the block from the
// real Cobra tree and holds the committed one against it. It reads the block
// between the markers rather than the whole file, so a command named anywhere
// else in README.md does not stand in for a missing row.
func TestReadmeCommandTableMatchesTheCommandTree(t *testing.T) {
	readme, err := docsmd.Read(commandTableFile)
	if err != nil {
		t.Fatalf("reading %s: %v", commandTableFile, err)
	}
	_, rest, found := strings.Cut(readme, beginCommands)
	if !found {
		t.Fatalf("%s no longer carries the command block marker %q", commandTableFile, beginCommands)
	}
	block, _, found := strings.Cut(rest, endCommands)
	if !found {
		t.Fatalf("%s opens the command block but never closes it with %q", commandTableFile, endCommands)
	}

	c := newCLI(t)
	want := strings.TrimSpace(c.mustRun("docs", "--table").out)
	if got := strings.TrimSpace(block); got != want {
		t.Errorf("%s's command table is not what `tix docs --table` produces.\n"+
			"Regenerate the block between the markers.\n%s", commandTableFile, diffLines(got, want))
	}
}

// diffLines names the rows that differ, because a whole table printed twice
// leaves the reader to find the one line that moved.
func diffLines(got, want string) string {
	gotLines := strings.Split(got, "\n")
	wantLines := strings.Split(want, "\n")
	var b strings.Builder
	for _, line := range wantLines {
		if !slices.Contains(gotLines, line) {
			b.WriteString("missing from the command table: " + line + "\n")
		}
	}
	for _, line := range gotLines {
		if !slices.Contains(wantLines, line) {
			b.WriteString("in the command table but not in the command tree: " + line + "\n")
		}
	}
	if b.Len() == 0 {
		return "the rows differ only in order or spacing\n"
	}
	return b.String()
}
