// SPDX-License-Identifier: AGPL-3.0-or-later

package cmd

import (
	"slices"
	"strings"
	"testing"

	"github.com/heliopsy/tix/internal/docsmd"
)

// The comment README.md already carries around the command table claims the
// block is generated. Nothing enforced it, so the table lost a row and kept
// the claim: the block had no `tix demo` line for as long as anybody looked.
const (
	beginCommands = "<!-- BEGIN COMMANDS: generated by `tix docs --table`, do not edit by hand -->"
	endCommands   = "<!-- END COMMANDS -->"
)

// TestReadmeCommandTableMatchesTheCommandTree regenerates the block from the
// real Cobra tree and holds the committed one against it. It reads the block
// between the markers rather than the whole file, so a command named anywhere
// else in README.md does not stand in for a missing row.
func TestReadmeCommandTableMatchesTheCommandTree(t *testing.T) {
	readme, err := docsmd.Read("README.md")
	if err != nil {
		t.Fatalf("reading README.md: %v", err)
	}
	_, rest, found := strings.Cut(readme, beginCommands)
	if !found {
		t.Fatalf("README.md no longer carries the command block marker %q", beginCommands)
	}
	block, _, found := strings.Cut(rest, endCommands)
	if !found {
		t.Fatalf("README.md opens the command block but never closes it with %q", endCommands)
	}

	c := newCLI(t)
	want := strings.TrimSpace(c.mustRun("docs", "--table").out)
	if got := strings.TrimSpace(block); got != want {
		t.Errorf("README.md's command table is not what `tix docs --table` produces.\n"+
			"Regenerate the block between the markers.\n%s", diffLines(got, want))
	}
}

// diffLines names the rows that differ, because a whole table printed twice
// leaves the reader to find the one line that moved.
func diffLines(got, want string) string {
	gotLines := strings.Split(got, "\n")
	wantLines := strings.Split(want, "\n")
	var b strings.Builder
	for _, line := range wantLines {
		if !slices.Contains(gotLines, line) {
			b.WriteString("missing from README.md: " + line + "\n")
		}
	}
	for _, line := range gotLines {
		if !slices.Contains(wantLines, line) {
			b.WriteString("in README.md but not in the command tree: " + line + "\n")
		}
	}
	if b.Len() == 0 {
		return "the rows differ only in order or spacing\n"
	}
	return b.String()
}
